### ISSUE TITLE
Hardcode file order

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/BIO-BTE-06-L-7#6]
In a project like this, where the orde rof the docs in the sidebar is extremely important, it may be worth it to hardcode it here:

https://github.com/CSBiology/BIO-BTE-06-L-7/blob/15f96f03ce5621c6125df8eb0d705a85ac57c267/docs/_template.html#L57

so instead of the placeholder, use actual hardcoded links, at least until https://github.com/fsprojects/FSharp.Formatting/issues/616 is fixed

**Comment by Joott** [comment]
Fixed in commit https://github.com/CSBiology/BIO-BTE-06-L-7/commit/d83558f723ffdccb97098f55ea45a476eb7f9d37.
